ipl/application/urls.py
from django.urls import re_path

from .views import *

urlpatterns = [
    re_path('driver/?$', DriverView.as_view(), name='driver'),
    re_path('truck/?$', TruckView.as_view(), name='truck'),
    re_path('consignee/?$', ConsigneeView.as_view(), name='consignee'),
    re_path('consignor/?$', ConsignorView.as_view(), name='consignor'),
    re_path('landingpage/?$', LandingPageView.as_view(), name='landingpage'),
    re_path('challan/?$', LoadingChallanView.as_view(), name='loadingchallan'),
    re_path('bill-generation/?$', BillGenerationView.as_view(), name='billgeneration'),
    re_path('to-pay/?$', ToPayView.as_view(), name='to-pay'),
    re_path('reports/?$', ReportsView.as_view(), name='reports'),
    re_path('cashreceipt-report/?$', CashReceiptReportsView.as_view(), name='cash_receipt_report'),
    re_path('downloads/?$', DownloadsView.as_view(), name='order_download'),
    re_path('cashreceipt/?$', CashReceiptView.as_view(), name='cash_receipt'),
]

ipl/ipl/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path("", include(("account.urls", 'account'))),
    path("", include(("application.urls", 'application')))
]

ipl/application/models.py
from django.db import models
from django.db.models.deletion import CASCADE


def user_directory_path(instance, filename):
    return 'ipl/media/documents/driver/{0}_{1}'.format(instance.name, filename)


class DriverModel(models.Model):
    name = models.CharField(max_length=100)
    contact_number = models.BigIntegerField(default=None)
    alternate_contact = models.BigIntegerField(default=None)
    family_contact = models.BigIntegerField(default=None, null=True, blank=True)
    date_of_joining = models.DateField(default=None)
    license_number = models.CharField(max_length=100)
    license_document = models.FileField(upload_to=user_directory_path)
    address_permanent = models.CharField(max_length=300, default=None)
    address_temporary = models.CharField(max_length=300, default=None)
    created_dtm = models.DateTimeField(auto_now_add=True)
    updated_dtm = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'Driver'
        get_latest_by = 'created_dtm'
        ordering = ['name']


class TruckModel(models.Model):
    class TruckTypes(models.TextChoices):
        open_type = 'open', ('Open')
        close_type = 'close', ('Close')
    truck_number = models.CharField(max_length=100)
    no_of_wheels = models.IntegerField(default=None)
    model = models.CharField(max_length=100)
    feet = models.IntegerField(default=None)
    mileage = models.IntegerField(default=0, null=True, blank=True)
    manufacture_name = models.CharField(max_length=100)
    manufacture_date = models.DateField(default=None)
    truck_type = models.CharField(max_length=100, choices=TruckTypes.choices, default=None)
    tonnage = models.IntegerField(default=None)
    created_dtm = models.DateTimeField(auto_now_add=True)
    updated_dtm = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'Truck'
        get_latest_by = 'created_dtm'
        ordering = ['truck_number']


class ConsigneeModel(models.Model):
    name = models.CharField(max_length=150)
    contact_number = models.BigIntegerField()
    gstin = models.CharField(max_length=15)
    address = models.CharField(max_length=300)
    created_dtm = models.DateTimeField(auto_now_add=True)
    updated_dtm = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'Consignee'
        get_latest_by = 'created_dtm'


class ConsignorModel(models.Model):
    name = models.CharField(max_length=150)
    contact_number = models.BigIntegerField()
    gstin = models.CharField(max_length=15)
    address = models.CharField(max_length=300)
    created_dtm = models.DateTimeField(auto_now_add=True)
    updated_dtm = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'Consignor'
        get_latest_by = 'created_dtm'


class BillModel(models.Model):
    consignor = models.ForeignKey(ConsignorModel, on_delete=CASCADE)
    created_dtm = models.DateTimeField(auto_now_add=True)
    updated_dtm = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'bill'
        get_latest_by = 'created_dtm'


class LoadingChallanModel(models.Model):
    class ConsigneePlaces(models.TextChoices):
        indore = 'indore', ('Indore')
        nagpur = 'nagpur', ('Nagpur')
        pune = 'pune', ('Pune')
        secunderabad = 'secunderabad', ('Secunderabad')

    lc_no = models.AutoField(primary_key=True)
    billing_date = models.DateField(default=None)
    place_of_receipt = models.CharField(max_length=100, default="Coimbatore")
    place_of_delivery = models.CharField(max_length=100, choices=ConsigneePlaces.choices, default=None)
    driver = models.ForeignKey(DriverModel, on_delete=CASCADE)
    vehicle_no = models.ForeignKey(TruckModel, on_delete=CASCADE)
    supplier = models.CharField(max_length=45)
    weight = models.IntegerField(max_length=45)
    vehicle_hire = models.IntegerField()
    advance_amount = models.FloatField()
    balance_amount = models.FloatField()
    created_dtm = models.DateTimeField(auto_now_add=True)
    updated_dtm = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'LoadingChallan'
        get_latest_by = 'created_dtm'


class ShippingOrdersModel(models.Model):
    class TaxPayable(models.TextChoices):
        consignee = 'Consignee', ('Consignee')
        consignor = 'Consignor', ('Consignor')
        ipl = 'IPL', ('IPL')

    class PaymentStatus(models.TextChoices):
        to_pay = 'to_pay', ('To Pay')
        tbb = 'tbb', ('To be Billed')
        paid = 'paid', ('PAID')

    class ConsigneePlaces(models.TextChoices):
        indore = 'indore', ('Indore')
        nagpur = 'nagpur', ('Nagpur')
        pune = 'pune', ('Pune')
        secunderabad = 'secunderabad', ('Secunderabad')

    consignor = models.ForeignKey(ConsignorModel, on_delete=CASCADE)
    consignor_gst = models.CharField(max_length=15)
    consignor_place = models.CharField(max_length=100, default="Coimbatore")
    consignee = models.ForeignKey(ConsigneeModel, on_delete=CASCADE)
    consignee_gst = models.CharField(max_length=15)
    consignee_place = models.CharField(max_length=100, choices=ConsigneePlaces.choices, default=None)
    no_of_packages = models.CharField(max_length=100)
    package_value = models.IntegerField(null=True, default=None, blank=True)
    package_description = models.CharField(max_length=1000)
    actual_weight = models.FloatField(default=None, null=True)
    charged_weight = models.FloatField(default=None, null=True)
    amount_per_kg = models.FloatField(default=None, null=True)
    freight_charges = models.FloatField(default=None, null=True, blank=True)
    lr_charges = models.FloatField(default=None, null=True, blank=True)
    hamali_charges = models.FloatField(default=None, null=True, blank=True)
    door_collection = models.FloatField(default=None, null=True, blank=True)
    door_delivery = models.FloatField(default=None, null=True, blank=True)
    other_charges = models.FloatField(default=None, null=True, blank=True)
    total_charges = models.FloatField()
    paid_amount = models.FloatField(default=None, null=True)
    payment_status = models.CharField(max_length=20, choices=PaymentStatus.choices, default=None)
    invoice_no = models.CharField(max_length=100)
    invoice_date = models.DateField(default=None)
    billing_date = models.DateField(default=None)
    gs_tax_payable = models.CharField(max_length=100, choices=TaxPayable.choices, default=None)
    created_dtm = models.DateTimeField(auto_now_add=True)
    updated_dtm = models.DateTimeField(auto_now=True)
    loading_challan = models.ForeignKey(LoadingChallanModel, on_delete=CASCADE, default=None, null=True)
    bill = models.ForeignKey(BillModel, on_delete=CASCADE, default=None, null=True)

    class Meta:
        db_table = 'Orders'
        get_latest_by = 'created_dtm'


class PaymentNotificationModel(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    sent = models.DateTimeField(default=False)

    class Meta:
        db_table = 'payment_notification'
        get_latest_by = 'date'


class CashReceiptsModel(models.Model):
    gc_no = models.CharField(max_length=100)
    received_from = models.CharField(max_length=125)
    receipt_date = models.DateField(default=None)
    booked_from = models.CharField(max_length=125)
    booked_to = models.CharField(max_length=125)
    total_amount = models.FloatField()
    payment_status = models.CharField(max_length=100, default="")
    created_dtm = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'cash_receipts'

ipl/application/forms.py
from django import forms

from django.forms import ModelForm

from .models import *

GENDER_CHOICES = (
    (None, '-None-'),
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Transgender', 'Transgender')
)


class DriverForm(ModelForm):
    class Meta:
        model = DriverModel
        exclude = ['created_dtm', 'updated_dtm']

    def clean(self):
        return self.cleaned_data


class TruckForm(ModelForm):
    class Meta:
        model = TruckModel
        exclude = ['created_dtm', 'updated_dtm']

    def clean(self):
        return self.cleaned_data


class ConsigneeForm(ModelForm):
    class Meta:
        model = ConsigneeModel
        exclude = ['created_dtm', 'updated_dtm']

    def clean(self):
        return self.cleaned_data


class ConsignorForm(ModelForm):
    class Meta:
        model = ConsignorModel
        exclude = ['created_dtm', 'updated_dtm']

    def clean(self):
        return self.cleaned_data


class BillForm(ModelForm):
    class Meta:
        model = BillModel
        exclude = ['created_dtm', 'updated_dtm']


class LoadingChallForm(ModelForm):
    class Meta:
        model = LoadingChallanModel
        exclude = ['created_dtm', 'updated_dtm']
        widgets = {
            'billing_date': forms.DateInput(
                attrs={
                    'type': 'date'
                }
            )
        }


class ShippingOrdersForm(ModelForm):
    class Meta:
        model = ShippingOrdersModel
        exclude = ['created_dtm', 'updated_dtm', 'loading_challan', 'bill']
        widgets = {
            'freight_charges': forms.NumberInput(
                attrs={
                    'class': 'form-control charges'
                }
            ),
            'lr_charges': forms.NumberInput(
                attrs={
                    'class': 'form-control charges'
                }
            ),
            'hamali_charges': forms.NumberInput(
                attrs={
                    'class': 'form-control charges'
                }
            ),
            'door_collection': forms.NumberInput(
                attrs={
                    'class': 'form-control charges'
                }
            ),
            'door_delivery': forms.NumberInput(
                attrs={
                    'class': 'form-control charges'
                }
            ),
            'other_charges': forms.NumberInput(
                attrs={
                    'class': 'form-control charges'
                }
            ),
            'total_charges': forms.NumberInput(
                attrs={
                    'class': 'form-control total-charges'
                }
            ),
            'charged_weight': forms.NumberInput(
                attrs={
                    'class': 'form-control freight-calculation'
                }
            ),
            'amount_per_kg': forms.NumberInput(
                attrs={
                    'class': 'form-control freight-calculation'
                }
            )
        }

    def clean(self):
        return self.cleaned_data

ipl/application/templates/app_static_content.html
{% extends 'base.html' %}
{% load static %}
{%block title %}Loading Challan{% endblock title %}
{% block body_content %}
 <div class="wrapper">
  <div class="container">
      <div class="row">
          <div class="col-sm-12">
              <h4 class="text-danger">No Data Found</h4>
          </div>
      </div>
  </div>
 </div>
{% endblock body_content %}

ipl/application/templates/to_pay.html
{% extends 'base.html' %}
{% load static %}
{% load subtract %}
{%block title %}TO PAY Customers{% endblock title %}
{% block other_styles %}
<style>
   hr.rounded {
   border-top: 3px dashed #bbb;
   border-radius: 5px;
   }
   .form-control{
   border:1px solid black;
   }
   .form-group{
   margin-bottom: 25px;
   }
   h5{
   margin-bottom: 15px;
   }
</style>
{% endblock other_styles %}
{% block modal-title %}Payment Status Update{% endblock modal-title %}
{% block body_content %}
<div class="main-content">
   <div class="wrapper">
      <div class="container">
         <h2 class="mb-4 ">{% block section_heading %}{% endblock section_heading %}</h2>
         <form method="POST" name="update-payment form" action="" >
            {% csrf_token %}
            <div class="form-group row">
               <div class="col-sm-6 has-feedback">
                   <input type="hidden" id="to-pay-ids" name="order_list"  value="">
               </div>
            </div>
         </form>
      </div>
      {% if update_status %}
         <h3 class="text-success">Payment Status updated Successfully</h3>
      {% endif %}

      {% if result_set|length == 0 %}
               <h3 class="text-success">No Orders found with Payment Status - TOPAY</h3>
      {% endif %}
      <div class="row"  id="matched-orders">
         <div class="table-wrapper-scroll-y my-custom-scrollbar">

            <h5>Orders with the status <b><u>TO PAY</u></b></h5>
            <div class="container mt-100">
               <div class="row">
                  <div class="col-md-12">
                     <div class="card">
                        <div class="card-header">
                           <table class="table table-bordered" id="ordersTable" >
                              <thead>
                                 <tr>
                                    <th scope="col">G.R.NO</th>
                                    <th scope="col">DATE</th>
                                    <th scope="col">FROM</th>
                                    <th scope="col">TO</th>
                                    <th scope="col">AMOUNT</th>
                                 </tr>
                              </thead>
                              <tbody>
                                 {% for result in result_set %}
                                 <tr>
                                    <td>{{result.id}}</td>
                                    <td>{{result.created_dtm|date:"d.m.y"}}</td>
                                    <td>{{result.consignor_place}}</td>
                                    <td>{{result.consignee_place}}</td>
                                    <td>{{result.total_charges}}</td>
                                 </tr>
                                 {% endfor %}
                              </tbody>
                           </table>
                           <div class="form-group" >
                              <div class="controls col-md-8 ">
                                 <button id="update-as-paid" type="button" class="btn btn-primary">
                                 Update as Paid
                                 </button>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock body_content %}
{% block other_scripts %}
<script>
{% if result_set|length > 0 %}
    $('#matched-orders').show();
{% else %}
    $('#matched-orders').hide();
{% endif %}
   $('input').addClass("form-control");
   $(".driver-contact").hide();
   $('select[name=place_of_delivery]').addClass("form-control");
   $('select[name=driver]').addClass("form-control");
   $('input[type=date]').attr("required");
   $('select[name=driver]').attr("required");
      $(document).ready(function() {
        $("#ordersTable").DataTable();
        $('.dataTables_length').addClass('bs-select');

       $("#update-as-paid").hide();
       $('#ordersTable tbody').on( 'click', 'tr', function () {
            $(this).toggleClass('selected');
            if ($('.selected').length > 0){
               $("#update-as-paid").show();
            }
            else{
               $("#update-as-paid").hide();
            }
        });
      });
    $('#update-as-paid').click( function () {
         var order_list = []
         $('.selected').each(function(){
           order_list.push($(this).children('td:first').html());
         });
         $('#to-pay-ids').val(""+order_list);
         validateAndShowModal();
    });
</script>

{% endblock other_scripts %}

ipl/application/templates/truck.html
{% extends 'base.html' %}
{% load static %}
{%block title %}Truck Details{% endblock title %}
{% block other_styles %}
<style xmlns="http://www.w3.org/1999/html">
    hr.rounded {
      border-top: 3px dashed #bbb;
      border-radius: 5px;
    }
    .form-control{
        border:1px solid black;
    }
    .form-group{
        margin-bottom: 25px;
    }
    h5{
        margin-bottom: 15px;
    }

</style>
{% endblock other_styles %}
{% block modal-title %}Truck Update{% endblock modal-title %}
{% block body_content %}
<div class="main-content">
     <div class="wrapper">
        <div class="container">
            {% if upload_status %}
                <div class="alert alert-success"><i class="fa fa-check"></i>Truck Added Successfully</div>
            {% endif %}
            {% if truck_exists %}
                <div class="alert alert-danger">Truck number already Exist, Please verify</div>
            {% endif %}
            {% if deleted %}
                <div class="alert alert-danger">Truck(s) deleted successfully</div>
            {% endif %}
            <div class="col-sm-20">
                <div class="row">
                    <form method="POST" name="delete-form" action="" enctype="multipart/form-data">
                                {% csrf_token %}
                        <div class="form-group row">
                            <div class="col-sm-6 has-feedback">
                              <input type="hidden" id="delete-ids" name="delete_list"  value="">
                            </div>
                        </div>
                    </form>
                    <form method="POST" name="order-form" action="" enctype="multipart/form-data">
                        <h5><u>Add Truck</u></h5>
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-10"><!--left side -->
                                <div class="form-group row">
                                    <label for="{{form.truck_number.id_for_label}}" class="col-sm-6 col-form-label">
                                        Truck No:</label>
                                    <div class="col-sm-6 has-feedback">
                                        {{form.truck_number}}
                                        <div class="help-block error">
                                            <span for="{{ form.truck_number.html_name }}">{{ form.truck_number.errors.as_text | cut:"* " }}</span>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="{{form.no_of_wheels.id_for_label}}"
                                           class="col-sm-6 col-form-label">No.Of.Wheels
                                        :</label>
                                    <div class="col-sm-6 has-feedback">
                                        {{form.no_of_wheels}}
                                        <div class="help-block error">
                                            <span for="{{ form.no_of_wheels.html_name }}"></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="{{form.model.id_for_label}}" class="col-sm-6 col-form-label">                                      Model:</label>
                                    <div class="col-sm-6 has-feedback">
                                        {{form.model}}
                                        <div class="help-block error">
                                            <span for="{{ form.model.html_name }}">{{ form.model.errors.as_text | cut:"* " }}</span>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="{{form.feet.id_for_label}}" class="col-sm-6 col-form-label">Feet:</label>
                                    <div class="col-sm-6 has-feedback">
                                        {{form.feet}}
                                        <div class="help-block error">
                                            <span for="{{ form.feet.html_name }}">{{ form.feet.errors.as_text | cut:"* " }}</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="{{form.truck_type.id_for_label}}"
                                           class="col-sm-6 col-form-label">Truck Type:
                                    </label>
                                    <div class="col-sm-6 has-feedback">
                                        {{form.truck_type}}
                                            <div class="help-block error"><span for="{{ form.truck_type.html_name }}">{{ form.truck_type.errors.as_text | cut:"* " }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-10">


                                <div class="form-group row">
                                    <label for="{{form.mileage.id_for_label}}" class="col-sm-6 col-form-label">Mileage:
                                    </label>
                                    <div class="col-sm-6 has-feedback">
                                        {{form.mileage}}
                                        <div class="help-block error">
                                            <span for="{{ form.mileage.html_name }}">{{ form.mileage.errors.as_text | cut:"* " }}</span>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="{{form.manufacture_name.id_for_label}}"
                                           class="col-sm-6 col-form-label">Manufacture Name:</label>
                                    <div class="col-sm-6 has-feedback">
                                        {{form.manufacture_name}}
                                        <div class="help-block error">
                                            <span for="{{ form.manufacture_name.html_name }}">{{ form.manufacture_name.errors.as_text | cut:"* " }}</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="{{form.manufacture_date.id_for_label}}"
                                           class="col-sm-6 col-form-label">Manufacture Date:</label>
                                    <div class="col-sm-6 has-feedback">
                                        <input name="manufacture_date" type="date" id="manufacture_date" required>
                                        <div class="help-block error">
                                            <span for="{{ form.manufacture_date.html_name }}">{{ form.manufacture_date.errors.as_text | cut:"* " }}</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="{{form.tonnage.id_for_label}}"
                                           class="col-sm-6 col-form-label">Tonnage:</label>
                                    <div class="col-sm-6 has-feedback">
                                        {{form.tonnage}}
                                        <div class="help-block error">
                                            <span for="{{ form.tonnage.html_name }}">{{ form.tonnage.errors.as_text | cut:"* " }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div><!--right side -->
                        </div>
                        <div class="form-group">
                            <div class="aab controls col-md-4 "></div>
                            <div class="controls col-md-2 ">
<button type="button" class="btn btn-primary" onclick="validateAndShowModal()">
  Submit
</button>                                 </div>
                        </div>
                     </form>
                </div>


            </div>
        </div>

                             <div class="row">

                        <div class="table-wrapper-scroll-y my-custom-scrollbar">
                    <h5>Available Truck List:</h5>
<div class="container mt-100">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">

      <table class="table table-bordered" id="iplTable" >
        <thead>
          <tr>
            <th scope="col" style="display:none;">Id</th>
            <th scope="col">Truck Number</th>
            <th scope="col">Model</th>
            <th scope="col">No.Of.wheels</th>
            <th scope="col">Feet</th>
            <th scope="col">Mileage</th>
            <th scope="col">Truck Type</th>
            <th scope="col">Manufacture Name</th>
            <th scope="col">Manufacture Date</th>
            <th scope="col">Tonnage</th>

          </tr>
        </thead>
        <tbody>
            {% for truck in trucks%}
          <tr>
            <td style="display:none;">{{truck.id}}</td>
            <td>{{truck.truck_number}}</td>
            <td>{{truck.model}}</td>
            <td>{{truck.no_of_wheels}}</td>
            <td>{{truck.feet}}</td>
            <td>{{truck.mileage}}</td>
            <td>{{truck.truck_type}}</td>
            <td>{{truck.manufacture_name}}</td>
            <td>{{truck.manufacture_date}}</td>
            <td>{{truck.tonnage}}</td>
          </tr>
            {% endfor %}
        </tbody>
      </table>
                           <div class="form-group" >
                              <div class="controls col-md-8 ">
                                 <button id="delete-button" type="button" class="btn btn-primary">
                                 Delete
                                 </button>
                              </div>
                           </div>
                </div>
            </div>        </div>
    </div>
</div>
    </div>

                    </div>
     </div>
</div>
{% endblock body_content %}
{% block other_scripts %}
<script>
    $('#id_truck_type').append(`<option value="" selected>---------</option>`);
    $('#id_no_of_wheels').attr("min", 1);
    $('#id_no_of_wheels').attr("max", 12);
    $('input').addClass("form-control");
    $('select[name=truck_type]').addClass("form-control");
    $('input[type=date]').attr("required");

    $("#delete-form-submit").hide();
    $("#form-submit").show();
    function toggleSubmitButtons(){
        if($("#delete-form-submit").is(":visible")){
            $("#delete-form-submit").hide();
            $("#form-submit").show();
        }
        else{
            $("#delete-form-submit").show();
            $("#form-submit").hide();
        }
    }
    $(document).ready(function() {
      $("#delete-button").hide();

      $("#iplTable").DataTable();
      $('.dataTables_length').addClass('bs-select');
       $('#iplTable tbody').on( 'click', 'tr', function () {
            $(this).toggleClass('selected');
            if ($('.selected').length > 0){
               $("#delete-button").show();
            }
            else{
               $("#delete-button").hide();
            }
        });
    $('#delete-button').click( function () {
         var delete_list = []
         $('.selected').each(function(){
           delete_list.push($(this).children('td:first').html());
         });
         $('#delete-ids').val(""+delete_list);
            toggleSubmitButtons();
         $('#popupModal').modal('show');
    });
    });
</script>
{% endblock other_scripts %}